<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Blue_marker_1</name>
   <tag></tag>
   <elementGuidId>cb6fafec-db4a-4f7b-99b1-b6ad18d73997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='marker-label'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='marker-label'])[2]</value>
      <webElementGuid>034be39f-c594-456c-88ce-9d144601a509</webElementGuid>
   </webElementProperties>
</WebElementEntity>
