<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>red_marker1</name>
   <tag></tag>
   <elementGuidId>57c9edf5-6c42-4701-a26b-701060ed1753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;marker-label&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;marker-label&quot;])[1]</value>
      <webElementGuid>51bcfda9-39e5-414e-84de-dfd26251a521</webElementGuid>
   </webElementProperties>
</WebElementEntity>
