<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phy_all_</name>
   <tag></tag>
   <elementGuidId>18ff6f82-4a34-4638-9a5f-40ee8c7405c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@title=&quot;PDMER_PHY_TEST_ALL_UUT&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@title=&quot;PDMER_PHY_TEST_ALL_UUT&quot;]</value>
      <webElementGuid>aa8eba3a-62ce-4936-9665-39d388ee003b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
