<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Timeout_Popup_Checkbox</name>
   <tag></tag>
   <elementGuidId>c1b6deb1-8530-4422-8032-8c985fc6c4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@id='tcTimeoutPopupMessageCheckBox'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@id='tcTimeoutPopupMessageCheckBox'])[1]</value>
   </webElementProperties>
</WebElementEntity>
