<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Application_Version_Mainbar</name>
   <tag></tag>
   <elementGuidId>1fce1495-02b0-453d-845c-3ace21e698dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@class='navbar-primaryText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@class='navbar-primaryText']</value>
   </webElementProperties>
</WebElementEntity>
