<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Device Data</name>
   <tag></tag>
   <elementGuidId>422752e9-0517-4921-927c-6fe8070a925f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pcPort1GetDeviceDataBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pcPort1GetDeviceDataBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>551c9918-9fa3-4481-b4ac-e3e3efa1c217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcPort1GetDeviceDataBtn</value>
      <webElementGuid>36b7914a-5504-45b2-bc31-729376be3cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c5559e5-5a26-4477-88d1-79d09af0de3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grl-button-blue grl-getCapabilities-button btn btn-primary</value>
      <webElementGuid>06b54671-8e43-426a-b803-d3012a8ef5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Device Data</value>
      <webElementGuid>1de2c84a-f1e7-4797-9278-4d3bd2a6cb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcPort1GetDeviceDataBtn&quot;)</value>
      <webElementGuid>0dcc3a15-4c90-415e-acd5-e504435af466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pcPort1GetDeviceDataBtn']</value>
      <webElementGuid>5ad33ee6-a035-486b-b67a-184ca0fb978f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/div[4]/div[3]/div/button</value>
      <webElementGuid>cea9231b-8988-415c-8b21-60247fa7f2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Cable ( For Cable Testing )'])[1]/following::button[1]</value>
      <webElementGuid>f65c8094-b65c-408f-949a-81a13f486bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cable Selection'])[1]/following::button[2]</value>
      <webElementGuid>38ab8660-0c7c-4f2b-a02e-d2ee042d3e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Device Data'])[1]/preceding::button[1]</value>
      <webElementGuid>32ac430d-51c6-4c5c-958e-d9fc01faf67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUT Type'])[2]/preceding::button[2]</value>
      <webElementGuid>0bec1e43-4751-4e36-8642-d355016e3610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Device Data']/parent::*</value>
      <webElementGuid>0bb6e198-d1e2-4cbe-9c0a-9399a15ea420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/button</value>
      <webElementGuid>5cefc819-8d03-4015-833c-411ec4662d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pcPort1GetDeviceDataBtn' and @type = 'button' and (text() = 'Get Device Data' or . = 'Get Device Data')]</value>
      <webElementGuid>efd66b89-681b-4f88-a33a-d2605426da3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
