<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Load XML VIF File</name>
   <tag></tag>
   <elementGuidId>acff8612-6740-4fb0-a16c-5454a4871977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pcLoadXmlVifFileBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pcLoadXmlVifFileBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3e75aa3-0145-4703-88c4-6ba02fdd5d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcLoadXmlVifFileBtn</value>
      <webElementGuid>16619752-7511-47b6-bf3f-70dfbaab6579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a27b5783-c863-480e-b0e2-736e6ed906ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grl-button load-vif-button btn btn-primary</value>
      <webElementGuid>e8d71f86-670f-4f90-9b88-def998af7c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Load XML VIF File</value>
      <webElementGuid>f468649a-84cb-4436-bc6f-d6585ab58052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcLoadXmlVifFileBtn&quot;)</value>
      <webElementGuid>339d0454-b8fd-4255-9044-6338ea13307a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pcLoadXmlVifFileBtn']</value>
      <webElementGuid>8f172344-e6ab-48bb-9ec9-952961eb7b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/div[3]/div/button</value>
      <webElementGuid>39fb9139-454c-4f95-b107-6de69aed931d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load VIF'])[1]/following::button[1]</value>
      <webElementGuid>bd9ce406-5ab8-408e-9ee5-bb9a666dbe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informational (No VIF)'])[1]/following::button[1]</value>
      <webElementGuid>a2b7d2c9-22ee-4b6c-af95-e83e97b06f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New VIF'])[1]/preceding::button[1]</value>
      <webElementGuid>755050be-cfb4-4261-a080-635de34ce345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear VIF Data'])[1]/preceding::button[2]</value>
      <webElementGuid>05caec7a-1c90-4fc1-96f9-9df80fe971f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Load XML VIF File']/parent::*</value>
      <webElementGuid>9dddeb80-1d59-4083-a3c3-9fc01662ceaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>b081bbe0-125f-4dff-9735-36d9ff9d6a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pcLoadXmlVifFileBtn' and @type = 'button' and (text() = 'Load XML VIF File' or . = 'Load XML VIF File')]</value>
      <webElementGuid>f7b6b215-1ed6-40e7-b953-4665c270beb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
