<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>88945949-cde9-4392-8259-60536d76cc8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pcNewProjectNameSaveBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pcNewProjectNameSaveBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d810037-3452-42ba-ab57-80af98c1d142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcNewProjectNameSaveBtn</value>
      <webElementGuid>4a7c55c1-b79c-475b-b32e-e4f4f4e58152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53cbc7aa-53a7-4206-823c-4898389324f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grl-button btn-primary project-name-save-btn btn btn-primary</value>
      <webElementGuid>0b22fdb9-4dba-439f-be75-f8b15fbb4486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>e21d3851-1688-4271-9bf5-f971f44219ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcNewProjectNameSaveBtn&quot;)</value>
      <webElementGuid>3d3d08aa-8e9b-433c-9060-e9a314fb5fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pcNewProjectNameSaveBtn']</value>
      <webElementGuid>2829c5df-f4f3-4851-a82f-5a079854dffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>50e258ff-c05b-4529-bb28-4ee3ac972293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Name'])[1]/following::button[1]</value>
      <webElementGuid>c17bcea6-ca22-4d64-9280-6511891e38a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[14]/following::button[1]</value>
      <webElementGuid>71b74676-7d14-47dc-be62-f2cd15be363a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Test Mode'])[1]/preceding::button[1]</value>
      <webElementGuid>b6ad38cb-e194-406d-b43f-ccca13c87450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compliance'])[1]/preceding::button[1]</value>
      <webElementGuid>86154d92-260f-4883-932f-badc32ad5e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>e3ae99ba-a227-4746-a2c2-bd211d41e5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>e58d4421-e2e7-49de-8ad9-3522f6747c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pcNewProjectNameSaveBtn' and @type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>9a209f51-3113-4cb8-ad08-47bf8e66faf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
