<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Time  33.967616760  T  21106.80msVbu_5bc826</name>
   <tag></tag>
   <elementGuidId>01448d1f-8016-4812-b16e-0fb8abf66213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chart_toolbar_set_marker_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chart_toolbar_set_marker_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85018407-133e-4670-8912-4b12967604f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chart_toolbar_set_marker_button</value>
      <webElementGuid>82bdb9e0-5e91-4402-a7db-5c4e555b2f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e61693f5-af38-4555-8109-b3a0364e6459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plot-toolbar-btn btn btn-primary</value>
      <webElementGuid>6d91ec45-d37f-4740-8141-79b1b7490dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart_toolbar_set_marker_button&quot;)</value>
      <webElementGuid>fee6857b-993f-4f75-8167-4aa679062c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chart_toolbar_set_marker_button']</value>
      <webElementGuid>01143b80-ce2c-41d1-a581-340829608bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[4]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div[15]/button</value>
      <webElementGuid>02c66f7d-bacc-420a-a55d-9ad527cc2dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/button</value>
      <webElementGuid>70a74c1d-18a6-43e1-b7a7-5b8bcc2a095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chart_toolbar_set_marker_button' and @type = 'button']</value>
      <webElementGuid>ce39db25-288c-4291-aef9-bbdec99ac144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
