<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Channels_chartjs-render-monitor</name>
   <tag></tag>
   <elementGuidId>aa6aac1b-4090-4cfb-83ff-62f29c56a5be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.chartjs-render-monitor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chart-parent-div']/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>d1be5c43-8462-4093-bb28-fb6048bbddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>3ebb4fb9-d480-4929-bd41-799e52c7181b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1175</value>
      <webElementGuid>6c1f196d-4951-4c03-97cc-cec576494f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>da80a8ce-b2b9-4d96-800b-d00407fa53c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetElementId&quot;)/div[@class=&quot;channel-container&quot;]/div[@id=&quot;chart-parent-div&quot;]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
      <webElementGuid>9e0334c4-74cc-4d36-9d63-a85b82b04766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chart-parent-div']/canvas</value>
      <webElementGuid>7c7bcb3e-77c0-4de2-9fe7-6a23756eed1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>425ca46b-dc85-4412-b87f-cfc58a48390c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
