<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product Capability</name>
   <tag></tag>
   <elementGuidId>b9cfc70b-face-4796-ac43-8f2263f53912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-toggle-group']/label[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c86c8f50-d793-465e-9138-9567f0821088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-setIcon</value>
      <webElementGuid>eaae081d-0c8d-4493-bbe8-0bc1ebd11cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Capability</value>
      <webElementGuid>a6347915-2178-49a6-8856-faab854a04da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-toggle-group&quot;)/label[@class=&quot;leftbarButtonGroup leftNavItems btn btn-primary&quot;]/div[@class=&quot;custom-setIcon&quot;]</value>
      <webElementGuid>417b103c-16e2-4075-a944-af544b726122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-toggle-group']/label[2]/div</value>
      <webElementGuid>a0f1ae1d-1df8-4c23-b2f0-04ae30f66542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connection Setup'])[1]/following::div[1]</value>
      <webElementGuid>1304cfe1-6793-4a91-96aa-886e346bc7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set App Mode :'])[1]/following::div[13]</value>
      <webElementGuid>9b77eb4f-804f-45d3-95ba-917d5265b675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Config'])[1]/preceding::div[1]</value>
      <webElementGuid>7c00d98b-8c96-43ad-9312-79fa464b4d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div</value>
      <webElementGuid>eb46f337-3ed9-48ef-8053-390c43e7113b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Product Capability' or . = 'Product Capability')]</value>
      <webElementGuid>6c3aa7f4-b2f5-4fec-97e8-5fca0b7e511a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
