<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Time  33.967616760  T  21106.80msVbus  _62bfeb</name>
   <tag></tag>
   <elementGuidId>04cec3b8-df99-40a4-b1cc-2ec9bcc62e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.plot-toolbar-img.plot-toolbar-img2.undefined.grey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[4]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div[16]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0b4a7138-d395-442a-a87d-82e5b81d1bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/chartIcons/PNG/enable-disable-signal-markers.png</value>
      <webElementGuid>c92ecd25-a98a-40e6-ba92-d7a43e2a7246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>marker</value>
      <webElementGuid>25a79e4e-c847-49b9-947d-61a7fa5c99f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plot-toolbar-img plot-toolbar-img2 undefined grey</value>
      <webElementGuid>22cab6c2-a0ae-49aa-b763-6e409211f475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;SplitPane plotSplitPane vertical&quot;]/div[@class=&quot;Pane vertical Pane1&quot;]/div[@class=&quot;SplitPane plotSplitPane2 vertical&quot;]/div[@class=&quot;Pane vertical Pane2&quot;]/div[@class=&quot;panelplot-container&quot;]/div[1]/div[@class=&quot;setMaxHeight&quot;]/div[@class=&quot;markers-height&quot;]/div[@class=&quot;chart-obsolute-container&quot;]/div[1]/div[1]/div[@class=&quot;plot-toggle&quot;]/div[@class=&quot;chart-plottoolbar&quot;]/div[@class=&quot;toolbar_btn_div undefined&quot;]/button[@class=&quot;plot-toolbar-btn btn btn-primary&quot;]/img[@class=&quot;plot-toolbar-img plot-toolbar-img2 undefined grey&quot;]</value>
      <webElementGuid>e6ee1168-93b4-40d9-ab49-fcd0a847083a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[4]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div[16]/button/img</value>
      <webElementGuid>a17cf663-5167-4c8d-a923-eba577ae5774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='marker']</value>
      <webElementGuid>a49d015c-c0ae-4f2a-8a00-7e302e20f3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/button/img</value>
      <webElementGuid>0e806386-848d-47a2-94ee-afc8e1a60e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/chartIcons/PNG/enable-disable-signal-markers.png' and @alt = 'marker']</value>
      <webElementGuid>8fb218dc-f0d9-4df7-9c15-4b87298b2682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
