<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Time  33.967616760  T  21106.80msVbus  _20ad77_1</name>
   <tag></tag>
   <elementGuidId>b5498b74-13d8-4664-8647-0075a1adbd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chart_toolbar_pan_bottom_button > img.plot-toolbar-img.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chart_toolbar_pan_bottom_button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4255d125-ae7d-43f9-b0cc-716b03c4077e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/chartIcons/PNG/move-bottom.png</value>
      <webElementGuid>05d41011-114f-4802-8d60-710022892063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>hands</value>
      <webElementGuid>c3152dd7-a4ec-4f45-87cd-45d550c013cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plot-toolbar-img undefined</value>
      <webElementGuid>612d6a6d-a17a-4eb9-94f4-3a9d39ea6b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart_toolbar_pan_bottom_button&quot;)/img[@class=&quot;plot-toolbar-img undefined&quot;]</value>
      <webElementGuid>3575d490-0c39-4619-9ccf-217af8eeea2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='chart_toolbar_pan_bottom_button']/img</value>
      <webElementGuid>b76a5c9c-590e-412d-86e3-86391901145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='hands'])[4]</value>
      <webElementGuid>3d8f0084-ae15-4df0-b2b6-faf4998b29d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/button/img</value>
      <webElementGuid>4688653a-3a79-4c4d-bd3b-2382196dfc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/chartIcons/PNG/move-bottom.png' and @alt = 'hands']</value>
      <webElementGuid>55b8d674-4b5b-4e3f-b6b6-407433c07865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
