<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Time  33.967616760  T  21106.80ms_plot-_323741</name>
   <tag></tag>
   <elementGuidId>8a7e09d8-4893-4993-9f1a-909268c6f167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.plot-toolbar-img.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chart_toolbar_horizontal_zoom_in_button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9c5601f-075b-4d59-af76-4e49e4e06cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/chartIcons/PNG/Horizontal-zoom-in.png</value>
      <webElementGuid>88cf3396-176d-439c-ac58-ec9bce527425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>zoom-in</value>
      <webElementGuid>fb03eb0f-b4d2-47ce-a7f3-ed659826bf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plot-toolbar-img undefined</value>
      <webElementGuid>47a3ba23-184f-4f55-8de3-cca2734427ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart_toolbar_horizontal_zoom_in_button&quot;)/img[@class=&quot;plot-toolbar-img undefined&quot;]</value>
      <webElementGuid>649efa4d-abfa-4981-8bfb-b48abad06afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='chart_toolbar_horizontal_zoom_in_button']/img</value>
      <webElementGuid>1852edcc-5b46-403b-b819-aa6605ad978c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='zoom-in']</value>
      <webElementGuid>123db162-1c8e-4a32-a7c0-38182d73a591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/button/img</value>
      <webElementGuid>7be2b851-e281-40d4-b180-d4b91821d089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/chartIcons/PNG/Horizontal-zoom-in.png' and @alt = 'zoom-in']</value>
      <webElementGuid>258daffe-0df7-4fb2-ba88-eca7d0f805ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
