<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Time  33.967616760  T  21106.80ms_plot-_323741_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>bc939edd-d16c-451a-a716-063fd6c64651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chart_toolbar_pan_left_button > img.plot-toolbar-img.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chart_toolbar_pan_left_button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95ae7bbc-0052-4690-85cc-d51d0d3b7073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/chartIcons/PNG/move-left.png</value>
      <webElementGuid>94d6f97d-a3f8-4c49-ac36-1a5b27faa847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>hands</value>
      <webElementGuid>ff6eb010-8aa2-4df8-b20c-24772347ce16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plot-toolbar-img undefined</value>
      <webElementGuid>c911a697-0913-4deb-9199-9ca69fd77d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart_toolbar_pan_left_button&quot;)/img[@class=&quot;plot-toolbar-img undefined&quot;]</value>
      <webElementGuid>dba4c0fc-afdb-411c-b0a0-002846ee90fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='chart_toolbar_pan_left_button']/img</value>
      <webElementGuid>8df9f5e4-2ddb-4293-bf4c-f09a0e3045bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='hands'])[2]</value>
      <webElementGuid>229a5442-5318-4165-a661-a56c385c563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button/img</value>
      <webElementGuid>8690488c-9120-4930-9466-c64c23b02aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/chartIcons/PNG/move-left.png' and @alt = 'hands']</value>
      <webElementGuid>bd73a4d5-9455-4737-bf10-71f08a2992b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
