<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fetching Device Capability_plot-toolbar_f56865</name>
   <tag></tag>
   <elementGuidId>4ce010e8-5a34-4d92-a286-5170fde1cce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[4]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[17]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>69a37921-d4db-4fb3-b714-6296b5d376fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/chartIcons/PNG/mask.png</value>
      <webElementGuid>a570c2d9-9352-4380-9327-6ebb5063be45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>mask</value>
      <webElementGuid>a20757e8-374b-41f9-9e24-0bfd99e6c11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plot-toolbar-img undefined</value>
      <webElementGuid>de8baafc-3241-4778-ae6a-e2a5b45a8d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;SplitPane plotSplitPane vertical&quot;]/div[@class=&quot;Pane vertical Pane1&quot;]/div[@class=&quot;SplitPane plotSplitPane2 vertical&quot;]/div[@class=&quot;Pane vertical Pane2&quot;]/div[@class=&quot;panelplot-container&quot;]/div[1]/div[@class=&quot;setMaxHeight&quot;]/div[@class=&quot;markers-height&quot;]/div[@class=&quot;chart-obsolute-container&quot;]/div[1]/div[1]/div[@class=&quot;plot-toggle&quot;]/div[@class=&quot;chart-plottoolbar&quot;]/div[@class=&quot;toolbar_btn_div undefined&quot;]/button[@class=&quot;plot-toolbar-btn btn btn-primary&quot;]/img[@class=&quot;plot-toolbar-img undefined&quot;]</value>
      <webElementGuid>16e5401a-f57f-4971-abd4-b61756b8a7b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[4]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[17]/button/img</value>
      <webElementGuid>203a799d-e68a-4a5a-a47e-aff04efe7a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='mask']</value>
      <webElementGuid>43f16ed2-b60d-496a-b62a-0fe027041845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/button/img</value>
      <webElementGuid>271be81a-441c-4165-863b-fa704f5f5014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/chartIcons/PNG/mask.png' and @alt = 'mask']</value>
      <webElementGuid>d87dad08-ebc5-4e08-87d8-542c8880cc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
