<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project Name_pcNewProjectNameInputField</name>
   <tag></tag>
   <elementGuidId>26fb6d9b-0695-4349-ad5f-2f025625fcbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pcNewProjectNameInputField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pcNewProjectNameInputField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c5f600e-c546-4193-a9ea-f2ef3d55708a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb3b7c50-e4a7-43d9-b8a0-b415071745f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-name-input </value>
      <webElementGuid>4dca0fc4-055a-45f9-bd3e-4d1a845548de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcNewProjectNameInputField</value>
      <webElementGuid>021880e4-f234-45b8-bd1f-aa65d5bde4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DRP34 DEBUGunit sc lab proper</value>
      <webElementGuid>dabb6e85-1403-46f3-b47f-a28c7d4be9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcNewProjectNameInputField&quot;)</value>
      <webElementGuid>92e0b913-ff6f-48d2-930f-78b252bad004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pcNewProjectNameInputField']</value>
      <webElementGuid>9f92fee0-b1ca-48fb-aee8-e33cb7e6e0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>4e20f3fa-727b-475c-9b8d-7ec07a5689a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>28209d52-a73d-417f-864b-55ca1173723c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pcNewProjectNameInputField']</value>
      <webElementGuid>4db96474-f370-4255-b1e0-1e5753b5b138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
