<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2nd_current</name>
   <tag></tag>
   <elementGuidId>3f0d65be-4396-4f90-b0ce-237b5b630700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[5]</value>
      <webElementGuid>3e1fa696-34b9-4d2f-8f99-d6f9aed36553</webElementGuid>
   </webElementProperties>
</WebElementEntity>
