<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2nd_voltage</name>
   <tag></tag>
   <elementGuidId>3526e7b4-b1bb-40b0-ba58-bb1517d72384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[4]</value>
      <webElementGuid>d65f5ce0-d8cb-49f7-b099-8305cc3befff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
