<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5th_current</name>
   <tag></tag>
   <elementGuidId>5f55bf86-324b-4cc2-9849-292b76bad23f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[11]</value>
      <webElementGuid>dabf50a7-749e-4f4e-85cc-4e61a9b75da5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
