<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5th_voltage</name>
   <tag></tag>
   <elementGuidId>cac6635c-f56b-4fc5-abec-2cca7688415f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[10]</value>
      <webElementGuid>ff1b5ebf-ffbb-4155-80f1-b6b3d36a5266</webElementGuid>
   </webElementProperties>
</WebElementEntity>
