<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>6th_volatge</name>
   <tag></tag>
   <elementGuidId>a13ccb61-65c9-4813-a363-90eb69611702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[12]</value>
      <webElementGuid>0cf9d383-1dd3-423a-9901-9945fef4895e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
