<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7th_voltage</name>
   <tag></tag>
   <elementGuidId>ecc98d1c-3a78-4a48-bde4-f9178c058e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[14]</value>
      <webElementGuid>d597fc9c-95a0-4346-b121-af7b10b5831d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
