<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7th_current</name>
   <tag></tag>
   <elementGuidId>9b640b9b-fdda-4682-be1d-a79dbe14fba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[15]</value>
      <webElementGuid>657894f4-baa4-4073-be84-f94d8feec8c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
