<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Send</name>
   <tag></tag>
   <elementGuidId>238985be-1146-4180-af98-26d8c899dbc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;send-btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;send-btn&quot;]</value>
      <webElementGuid>80ee287c-df3e-4556-8dc1-3d19d89027f1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
