<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_start</name>
   <tag></tag>
   <elementGuidId>6e782361-fe1e-4eb2-9ea2-11fa104bfaac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;opConfigControllerConfigureStartBtn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;opConfigControllerConfigureStartBtn&quot;]</value>
      <webElementGuid>99c9d817-2217-4f72-a997-3b5b3b8d57e8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
