<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Data</name>
   <tag></tag>
   <elementGuidId>f6fc19fd-29be-4307-b1a7-5dc00781916e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@value=&quot;DataMessageTypes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@value=&quot;DataMessageTypes&quot;]</value>
      <webElementGuid>a5707f72-7cf0-4361-8376-8d1ea2d35a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@value=&quot;DataMessageTypes&quot;]</value>
      <webElementGuid>864aaeaf-df78-4f08-8310-14f90b46dede</webElementGuid>
   </webElementProperties>
</WebElementEntity>
