<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_cc2</name>
   <tag></tag>
   <elementGuidId>4c8c7fea-427d-4f48-b95a-8da4f316f212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;opConfigControllerConfigureChannelsCC2heckBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;opConfigControllerConfigureChannelsCC2heckBox&quot;]</value>
      <webElementGuid>996c5197-823a-4bb8-85ce-a99768e9758b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
