<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter_current</name>
   <tag></tag>
   <elementGuidId>be2dea9f-4cc1-4b6e-8ab1-a18c0967fa30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[3]</value>
      <webElementGuid>24e0671f-ed55-455c-b4ca-d93cda815e6e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
