<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nd_voltage</name>
   <tag></tag>
   <elementGuidId>defc6ea1-53c5-4947-8878-921d90225ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[4]</value>
      <webElementGuid>10b305bc-2809-47b5-9b84-4c877f92c77b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
