<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Save_File_text</name>
   <tag></tag>
   <elementGuidId>cd8ba928-3b5a-4a0f-918b-8dc88fbc6934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@class=&quot;popup-heder-font-align&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[@class=&quot;popup-heder-font-align&quot;]</value>
   </webElementProperties>
</WebElementEntity>
