<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eload_Channel_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>c1b3ffe3-4222-460f-b478-47d4e316dc63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcMfiChargerELoadChannelComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcMfiChargerELoadChannelComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
