<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manufacturer_Info</name>
   <tag></tag>
   <elementGuidId>7c76f5b9-ca36-4043-bcdb-f0fe5e19847d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;tcReportManufacturerInputField&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;tcReportManufacturerInputField&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;tcReportManufacturerInputField&quot;]</value>
   </webElementProperties>
</WebElementEntity>
