<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Model_Number</name>
   <tag></tag>
   <elementGuidId>a5783dda-fa61-448b-9c13-7e6aa9fa48ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tcReportModelNumberInputField&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tcReportModelNumberInputField&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tcReportModelNumberInputField&quot;]</value>
   </webElementProperties>
</WebElementEntity>
