<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Grl_Banner_img</name>
   <tag></tag>
   <elementGuidId>d4d42315-0f0e-40f9-8b59-48ac667ac10c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/img[@class='grl-bannerImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/img[@class='grl-bannerImg']</value>
   </webElementProperties>
</WebElementEntity>
