<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Port_POPup</name>
   <tag></tag>
   <elementGuidId>7c112413-b881-42a4-9339-11026787ce41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@class=&quot;popup-heder-font-align&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[@class=&quot;popup-heder-font-align&quot;]</value>
   </webElementProperties>
</WebElementEntity>
