<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sucessfull_update</name>
   <tag></tag>
   <elementGuidId>e28bdbe1-096b-4f22-8b66-ead68474139b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@class=popup-heder-font-align&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[@class=popup-heder-font-align&quot;]</value>
   </webElementProperties>
</WebElementEntity>
