<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DataMessageTypes</name>
   <tag></tag>
   <elementGuidId>354402c5-e809-4fb0-8b5f-db09c8593520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@value='DataMessageTypes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f6a59bb-5a15-4e22-99de-fc1fd19e77b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DataMessageTypes</value>
      <webElementGuid>940342ef-0582-4957-a93b-eb8e636eda11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>961f1290-7c44-4a87-9c4e-0d1569463351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6cf3741-d5a2-4b5a-a6be-76097bf01a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b22cf0bf-59a6-4b8c-a87c-70b083646391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DataMessageTypes</value>
      <webElementGuid>82719bcd-327e-418e-8797-750bab8d6f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[1]/td[2]/div[@class=&quot;config-control-dropdown-flex show dropdown&quot;]/div[@class=&quot;config-dropdown-menu dropdown-menu show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>5533e3f5-fa66-4494-98d9-5da454dd5481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4266832-e76b-4a83-ba47-ab180355d18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DataMessageTypes</value>
      <webElementGuid>6f36cac8-f7eb-4b09-884a-2506276176e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>81670de0-9e9c-475c-94b1-98404d0d5536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7894680f-8d27-43c9-8a49-782dfc6ecccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3d7865fe-81e2-4726-a850-835892772a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DataMessageTypes</value>
      <webElementGuid>3d23a8df-9a29-4d19-9804-26518ae6f22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[1]/td[2]/div[@class=&quot;config-control-dropdown-flex show dropdown&quot;]/div[@class=&quot;config-dropdown-menu dropdown-menu show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>b55fbfbc-7915-4a78-97c7-efafde9a602d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@value='DataMessageTypes']</value>
      <webElementGuid>6c510246-cbaa-4718-a74e-f0fc5536b3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='vif-edit-table']/tr/td[2]/div/div/a[2]</value>
      <webElementGuid>db25e3a6-3d91-44df-987a-ab5e68b2071c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DataMessageTypes')]</value>
      <webElementGuid>027c7ae6-474b-4ae4-8976-6db5f1a7fbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DataMessageTypes'])[1]/following::a[2]</value>
      <webElementGuid>265befec-fee3-4ec2-840a-6ca2606d6d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Header'])[1]/following::a[2]</value>
      <webElementGuid>8a89eff3-6aa8-4069-a8a2-090474ac982a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Type'])[1]/preceding::a[2]</value>
      <webElementGuid>07e9e9f0-a766-498f-803d-155664288fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[2]/preceding::a[2]</value>
      <webElementGuid>5a06c549-3bc2-4b81-96e1-d2d3c867fb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>6fb2ffa8-575d-4664-8a1b-76573624383b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>3072c436-92b9-4469-ac74-1caf484dc660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'DataMessageTypes' or . = 'DataMessageTypes')]</value>
      <webElementGuid>0eb28595-210e-430c-b1ae-f3fa5d36669d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
