<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Source_Capabilities</name>
   <tag></tag>
   <elementGuidId>5d3ed23b-9b46-44cf-ae0a-3ec74f9105c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@value='Source_Capabilities']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-config.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6cccf14-b7a6-4b5b-beac-feb14ac22188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Source_Capabilities</value>
      <webElementGuid>1e892b7f-870b-4226-9f35-90d93eeda848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-config dropdown-item</value>
      <webElementGuid>c0ca49a4-3ec1-440d-9107-768492fa4fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>719542e3-3118-4cd5-ab16-a93211347375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>133b7e2b-777c-42d0-9378-837384180ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Source_Capabilities</value>
      <webElementGuid>8476a196-4499-4be4-9ace-fcae3ba27915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[2]/td[2]/div[@class=&quot;config-control-dropdown-flex show dropdown&quot;]/div[@class=&quot;config-dropdown-menu dropdown-menu show&quot;]/a[@class=&quot;dropdown-config dropdown-item&quot;]</value>
      <webElementGuid>48f63d5b-907d-4423-9b6e-6ab780315616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0550dfac-6979-4c08-b837-51770bf56859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Source_Capabilities</value>
      <webElementGuid>3041ef88-902b-4ad3-a756-e7a953c332c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-config dropdown-item</value>
      <webElementGuid>1db04b25-16ee-49f1-bdf2-2aed6d54cabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>833677e9-0788-49e9-b1ff-29c151b4487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>339994f8-c130-4563-8f9d-e70ea0f155a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Source_Capabilities</value>
      <webElementGuid>98b8495e-31a0-4f63-8699-6fc7e079cf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[2]/td[2]/div[@class=&quot;config-control-dropdown-flex show dropdown&quot;]/div[@class=&quot;config-dropdown-menu dropdown-menu show&quot;]/a[@class=&quot;dropdown-config dropdown-item&quot;]</value>
      <webElementGuid>d15b7aa6-7218-41d7-821b-4ec108dbbeb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@value='Source_Capabilities']</value>
      <webElementGuid>f79b5528-36da-4613-9575-48878ea1d23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='vif-edit-table']/tr[2]/td[2]/div/div/a</value>
      <webElementGuid>a00daad1-567c-44b3-a288-40b4caa3551a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Source_Capabilities')]</value>
      <webElementGuid>acd8413c-2674-47cb-82ea-2407e0e78a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Type'])[1]/following::a[1]</value>
      <webElementGuid>9d51997a-a914-4fa6-bd53-3fd2dff89f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DataMessageTypes'])[1]/following::a[4]</value>
      <webElementGuid>e24ecd4b-8961-471c-ae56-9e561412152d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[2]/preceding::a[13]</value>
      <webElementGuid>a152549f-026d-478d-bb13-cbef40237329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[2]/preceding::a[13]</value>
      <webElementGuid>c7f38eed-e7e3-45b9-b6e3-64fef7421d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Source_Capabilities']/parent::*</value>
      <webElementGuid>e5a46ca2-e46b-45f6-9ee1-85b7ea49e7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>e6ab6a38-4aa9-4b9e-b382-958da390de5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/a</value>
      <webElementGuid>f826a5c7-e2b7-4b8a-8c3c-e0c02a17a7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Source_Capabilities' or . = 'Source_Capabilities')]</value>
      <webElementGuid>260fa5cc-525b-40c8-a98b-76686a21cc20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
