<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connect</name>
   <tag></tag>
   <elementGuidId>3979e60c-8ab7-4b58-baa3-c5d0b2a53d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#csConnectBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='csConnectBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a555994-128f-4158-9802-05716142aa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>csConnectBtn</value>
      <webElementGuid>c5623910-a76a-4b36-90de-76de6ed78f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec3327fd-85f9-47f3-9bab-7acf09f15452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grl-connect-button grl-button connectionsetup-leftsideSetWidth btn btn-primary</value>
      <webElementGuid>90790ed2-79ec-45b0-a4b7-4f0c5f80d721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connect</value>
      <webElementGuid>a6e06b1c-1ff2-4fab-a179-473f651926b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csConnectBtn&quot;)</value>
      <webElementGuid>7d9cff09-1906-492b-8734-7d08beeae681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='csConnectBtn']</value>
      <webElementGuid>be703738-1b18-4211-a89e-097090e99bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div/div/div/div[4]/button</value>
      <webElementGuid>8bcf23cc-08ff-4afb-9962-548b0b2a1c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::button[1]</value>
      <webElementGuid>48843489-b681-408c-a32e-ac1c54506147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter/select C2 address'])[1]/following::button[1]</value>
      <webElementGuid>63feeb44-e9dd-401b-9d54-6d7dc58d89f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup Diagram'])[1]/preceding::button[1]</value>
      <webElementGuid>8f8da289-cf90-484d-8767-1d6ac3ce7bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tool Updates'])[1]/preceding::button[1]</value>
      <webElementGuid>7d5ff344-15e6-4fcb-8709-dfca0d66827b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connect']/parent::*</value>
      <webElementGuid>02169804-ead4-4c25-b269-366c22f4db6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>f93a63af-0be4-45f7-bcdf-879b3b81fb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'csConnectBtn' and @type = 'button' and (text() = 'Connect' or . = 'Connect')]</value>
      <webElementGuid>8ea07f70-fb5f-4a0d-8b07-1f88c933a508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
