<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Message Type_dropdowncustom dropdown_8ffbc8</name>
   <tag></tag>
   <elementGuidId>7118cff5-977b-4d29-9055-1b3bc60401f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[278]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e34156b-13eb-4bc0-962e-2f4a9f83b7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b917ddb8-8e82-4897-bf81-5c7b1df6f5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b826cb2e-750c-49b9-823c-79a2fa348288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3271976d-f93d-4dae-b5a6-3e89181a81e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdowncustom dropdown-toggle btn btn-success</value>
      <webElementGuid>f47550a5-611b-4b3f-8b55-1f0cf50e3b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[2]/td[2]/div[@class=&quot;config-control-dropdown-flex dropdown&quot;]/button[@class=&quot;dropdowncustom dropdown-toggle btn btn-success&quot;]</value>
      <webElementGuid>6382cbf7-5617-4da1-9f5c-25746f08702a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31aa6c0c-3023-4989-a61d-8d399c229a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3703171d-6ae8-40b9-92c6-b47ce5d2199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d32637a-2e91-45d1-94bf-904fb0a3c63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a44d5335-818f-4a50-8d2d-fc08adf246ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdowncustom dropdown-toggle btn btn-success</value>
      <webElementGuid>116a9175-665a-4bed-aa1e-389237bdbbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[2]/td[2]/div[@class=&quot;config-control-dropdown-flex dropdown&quot;]/button[@class=&quot;dropdowncustom dropdown-toggle btn btn-success&quot;]</value>
      <webElementGuid>e7b54107-c1a6-42b0-9ea5-458abf58bcbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[278]</value>
      <webElementGuid>cec08bab-bd80-4319-88af-873253bb5b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='vif-edit-table']/tr[2]/td[2]/div/button</value>
      <webElementGuid>5602f466-2583-45ff-b838-0ed3586e262e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]/div/button</value>
      <webElementGuid>d539ea43-186d-4644-b250-90ba6eae0684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>b287defd-c406-4f1c-b42b-85dbb004eb56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
