<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DataMessageTypes</name>
   <tag></tag>
   <elementGuidId>f47db931-aaaf-4b7a-8435-461ab7a09ac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[277]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22613212-273c-4510-bacc-4a4167521e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4fbc4e10-9799-450c-93f3-d9880bfa0713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd438abd-b57a-4aea-bbad-dc8a2f23dae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f57b6b23-bc44-4c38-98ac-6d9969c87832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdowncustom dropdown-toggle btn btn-success</value>
      <webElementGuid>6c9d0aa9-0cfc-4682-a266-b50f65bfb82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DataMessageTypes</value>
      <webElementGuid>3f8bdc6f-918a-4239-b559-f438ea848512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[1]/td[2]/div[@class=&quot;config-control-dropdown-flex dropdown&quot;]/button[@class=&quot;dropdowncustom dropdown-toggle btn btn-success&quot;]</value>
      <webElementGuid>ec8b90d6-b70c-4615-8d1c-73d91c8c9e13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[277]</value>
      <webElementGuid>e9329e32-90e4-43ff-ae31-93ca45b6a718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='vif-edit-table']/tr/td[2]/div/button</value>
      <webElementGuid>548233c1-c8b0-4661-bc92-71187477c80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Header'])[1]/following::button[1]</value>
      <webElementGuid>b0139612-ec92-460d-b8d6-f21f070fe4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data'])[1]/following::button[1]</value>
      <webElementGuid>1ae06f68-9e5e-43d0-828e-4708f8c315b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Type'])[1]/preceding::button[1]</value>
      <webElementGuid>bd86c744-1be8-4b19-b68e-7eb965e5e2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[2]/preceding::button[2]</value>
      <webElementGuid>b2f98196-a35a-4635-924d-40d78de3c9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DataMessageTypes']/parent::*</value>
      <webElementGuid>70ca3155-16d5-4ba7-955a-3dfc45b76bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td[2]/div/button</value>
      <webElementGuid>1f7b79e8-2316-49da-82a1-de158a969e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'DataMessageTypes' or . = 'DataMessageTypes')]</value>
      <webElementGuid>f48347a4-f24c-4a97-9b6e-2488d51057a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
