<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dual Role PowerDRP</name>
   <tag></tag>
   <elementGuidId>5fc4c1a5-1df0-4600-9354-d47d1882f660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pcPort1DutTypeComboBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pcPort1DutTypeComboBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0d1648b-f70d-4ab1-81d2-e3888dafb94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e89783a1-70c0-4001-9669-44684e96bb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a86e780e-2658-4e10-b695-d6f6d82c8249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcPort1DutTypeComboBox</value>
      <webElementGuid>f59b422b-e274-4468-be1d-b52d4d53a628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6301d004-675f-4577-82f1-8fca6fb90902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdowncustom dut-Dropdown dropdown-toggle btn btn-success</value>
      <webElementGuid>f05ee16f-20da-41d6-b135-9246c4d96a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dual Role Power[DRP]</value>
      <webElementGuid>ede6aa5f-10c3-4d2f-bdea-a353e40cd76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcPort1DutTypeComboBox&quot;)</value>
      <webElementGuid>e7ca0ffa-d9e7-483b-94ca-7dd97491e4c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pcPort1DutTypeComboBox']</value>
      <webElementGuid>32f7fa13-b1dd-4fe2-be7c-4a527de43c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/div[4]/div/div/div/button</value>
      <webElementGuid>e736adfe-ee27-42bb-9bdd-269abde2ba67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUT Type'])[1]/following::button[1]</value>
      <webElementGuid>050d1b9d-ecc4-43e0-8c0f-babcda989b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Off'])[1]/following::button[1]</value>
      <webElementGuid>674cb7a6-79e3-42a6-8ebc-08d1d555a60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cable Selection'])[1]/preceding::button[1]</value>
      <webElementGuid>e9f972a7-643d-4f8e-bcab-a69aba50e352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captive Cable'])[1]/preceding::button[1]</value>
      <webElementGuid>49f65613-0c67-4682-8b4b-40eceb1b1041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dual Role Power[DRP]']/parent::*</value>
      <webElementGuid>0676255f-e627-4167-a59b-b536cd1c2ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>0c91fe68-ad12-46ff-9347-09b578b4fccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pcPort1DutTypeComboBox' and @type = 'button' and (text() = 'Dual Role Power[DRP]' or . = 'Dual Role Power[DRP]')]</value>
      <webElementGuid>6fd4cb10-ef31-45b8-a554-43521e349133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
