<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Load XML VIF File</name>
   <tag></tag>
   <elementGuidId>17c336c4-311b-407b-bdaa-f18f7288ae16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pcLoadXmlVifFileBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pcLoadXmlVifFileBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf25408f-336d-4620-bffb-468cfe280ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcLoadXmlVifFileBtn</value>
      <webElementGuid>52ce2368-35da-423b-8893-b1614d237e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13fae07e-9080-47b8-ac8f-869eec92dc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grl-button load-vif-button btn btn-primary</value>
      <webElementGuid>1a4182ee-16ba-4b91-ba99-3825887eb02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Load XML VIF File</value>
      <webElementGuid>eacd2bba-d3c8-4242-8980-bcf1381abffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcLoadXmlVifFileBtn&quot;)</value>
      <webElementGuid>b9477e96-d76b-47b9-8909-91136d34bb37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pcLoadXmlVifFileBtn']</value>
      <webElementGuid>474aefe6-3d01-43f1-84a7-ce56d90b5bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/div[3]/div/button</value>
      <webElementGuid>a168987f-717a-4962-9c9e-044c43a63ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load VIF'])[1]/following::button[1]</value>
      <webElementGuid>38d9badc-8d66-46e4-aed4-85bd7f95fd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informational (No VIF)'])[1]/following::button[1]</value>
      <webElementGuid>eebef015-434d-469b-88ac-29f3ec28abba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New VIF'])[1]/preceding::button[1]</value>
      <webElementGuid>a59c64cc-cb3a-48a9-acf9-2ebdf26cb421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear VIF Data'])[1]/preceding::button[2]</value>
      <webElementGuid>7bdc43ff-1a70-4fcc-bb63-da928fff96b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Load XML VIF File']/parent::*</value>
      <webElementGuid>556f69b8-4cda-43ad-9e4a-90372d5c5a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>48cf92bb-4546-4ffb-9922-0ffb34368fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pcLoadXmlVifFileBtn' and @type = 'button' and (text() = 'Load XML VIF File' or . = 'Load XML VIF File')]</value>
      <webElementGuid>28125764-31bf-4251-a5b5-b8b08e019a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
