<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ethernet Connection Settings Scan Netwo_7cb67a</name>
   <tag></tag>
   <elementGuidId>71a8213f-609a-422e-9c04-a8017ded122a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.right-border.panel-padding.connectiondetails-mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cea05180-0366-47f2-abae-80a84379ff4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right-border panel-padding connectiondetails-mobile</value>
      <webElementGuid>0432d9bb-d88b-4cbf-855b-61c5025801b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ethernet Connection Settings Scan NetworkC2 IP AddressPlease enter/select C2 address192.168.4.232 ×ConnectSetup DiagramTool UpdatesUpdate FirmwareFirmware Update Instructions Update E-Load Firmware </value>
      <webElementGuid>53fbbdf7-a40d-4e5e-a954-6b284df13cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;main-mobile-container&quot;]/div[@class=&quot;right-border panel-padding connectiondetails-mobile&quot;]</value>
      <webElementGuid>c84ea6eb-25ee-4460-8aeb-d681b98f1e8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>aa4e93cb-6f34-49de-b51c-256971c43e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Mode'])[1]/following::div[8]</value>
      <webElementGuid>6338c955-a286-46af-92d2-3518db6b80ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::div[9]</value>
      <webElementGuid>33b7ea9b-7745-428a-a573-35e4b032c75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>0f405800-25cd-422f-b551-3410eaf06e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ethernet Connection Settings Scan NetworkC2 IP AddressPlease enter/select C2 address192.168.4.232 ×ConnectSetup DiagramTool UpdatesUpdate FirmwareFirmware Update Instructions Update E-Load Firmware ' or . = 'Ethernet Connection Settings Scan NetworkC2 IP AddressPlease enter/select C2 address192.168.4.232 ×ConnectSetup DiagramTool UpdatesUpdate FirmwareFirmware Update Instructions Update E-Load Firmware ')]</value>
      <webElementGuid>81bc13ed-7929-4102-96d0-eda2d4dc9e36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
