<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__rc-select-arrow-icon</name>
   <tag></tag>
   <elementGuidId>62d4e027-3ff7-4d16-b4fd-00b6f23be47d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div/div/div/div[4]/div/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.rc-select-arrow-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f6664afe-fc3c-4198-bfed-5a7fd2960a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-select-arrow-icon</value>
      <webElementGuid>df959bf6-1205-46ff-8b71-33adae5077ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;main-mobile-container&quot;]/div[@class=&quot;right-border panel-padding connectiondetails-mobile&quot;]/div[4]/div[@class=&quot;ip-address-textbox rc-select rc-select-combobox rc-select-enabled rc-select-allow-clear&quot;]/div[@class=&quot;rc-select-selection
            rc-select-selection--single&quot;]/span[@class=&quot;rc-select-arrow&quot;]/i[@class=&quot;rc-select-arrow-icon&quot;]</value>
      <webElementGuid>d8607a4e-7799-4fdd-9ecd-030648fcedbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div/div/div/div[4]/div/div/span[2]/i</value>
      <webElementGuid>02c58eba-2642-4c07-8b9a-eee9abbd67d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>84bfd1ed-dc80-41c5-8fc0-743423f86b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
