<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Report_leftnavbar-img</name>
   <tag></tag>
   <elementGuidId>f56f4cc4-cf78-483e-bcc7-947ff6ccb0d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-toggle-group']/label[6]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b611a690-c142-4f7e-856c-1c41fed6eb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/leftNavIcons/Options.png</value>
      <webElementGuid>3722843e-342c-47fa-88b6-80e8c08ef4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Options</value>
      <webElementGuid>b08bd1d9-3ba5-4161-98cb-7e289e56b713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftnavbar-img</value>
      <webElementGuid>3ff897dd-1aee-44ee-9618-df55d6c886c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-toggle-group&quot;)/label[@class=&quot;leftbarButtonGroup btn btn-primary&quot;]/div[@class=&quot;custom-setIcon&quot;]/img[@class=&quot;leftnavbar-img&quot;]</value>
      <webElementGuid>7d2b2452-6be7-4210-bb44-2de83f72c2ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-toggle-group']/label[6]/div/img</value>
      <webElementGuid>77923b45-43d7-4e52-9bda-1a2a1d0d1f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Options']</value>
      <webElementGuid>ba43bfaa-7940-4c7a-a290-22e8d98478bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[6]/div/img</value>
      <webElementGuid>db8000ad-4d02-452a-a761-7124ccdadf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/leftNavIcons/Options.png' and @alt = 'Options']</value>
      <webElementGuid>407cc112-44b0-476c-a48f-dee5bdb94f5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
