<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expand Test List_tcExpandTestListCheckBox</name>
   <tag></tag>
   <elementGuidId>dd5e714d-a55a-4351-89d1-38d48ea64383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tcExpandTestListCheckBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tcExpandTestListCheckBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb2285fc-3d1a-45a5-bfd8-86cdd996ff32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4390bd88-3a8b-40e3-a15d-e01854b67a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tcExpandTestListCheckBox</value>
      <webElementGuid>b92dcd1c-8968-4c26-92dd-3b9b2213445a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>functional-moi-checkbox</value>
      <webElementGuid>2cb05ad3-e9cb-41a4-af2c-de3064c02eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tcExpandTestListCheckBox&quot;)</value>
      <webElementGuid>d96bc64c-090d-40d3-8c36-d9004969a26a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tcExpandTestListCheckBox']</value>
      <webElementGuid>c63d61e2-927f-446e-b11d-da305402c8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[3]/div/div/div/div[4]/label/input</value>
      <webElementGuid>005dc273-b847-4128-9e70-f3bed99b5d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/input</value>
      <webElementGuid>1730c621-e51d-498c-8e25-ead3776f8c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'tcExpandTestListCheckBox']</value>
      <webElementGuid>3014799d-c625-41a8-a701-6566a78de673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
