<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Number of PDO, , s)_name</name>
   <tag></tag>
   <elementGuidId>f7cf7bf6-6c26-4f90-a7a9-5453102037f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab579938-62e6-4b21-a624-49059f05d4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3497b7c9-245d-4087-84dc-6de70a05d726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f538dd63-ef7f-4905-8de1-332c2e2177d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>config-editor-textbox</value>
      <webElementGuid>d77c24fe-a3fc-4829-8c26-fe422d4c6167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e0b2e6f4-5841-41ad-9c23-ad075cd68772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[3]/input[@class=&quot;config-editor-textbox&quot;]</value>
      <webElementGuid>34cf9922-3f74-4417-8eef-844d3b0fb073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e56f939c-01af-4247-91d7-ed392d905db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2356d761-07b4-4e19-9f2d-b7f46fd57acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>4de1f207-6a9c-42b3-9095-c417a1c3511f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>config-editor-textbox</value>
      <webElementGuid>7d21f1ee-cb9f-4515-8c05-230dc8640fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8dd369ce-9128-42a2-8e2e-9a5100749568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;panel-options-width&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade config-control-tab-pane tab-pane active show&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;panel-padding config-controller-width control scroll&quot;]/div[@class=&quot;config-table-div&quot;]/table[@id=&quot;vif-table&quot;]/tbody[@id=&quot;vif-edit-table&quot;]/tr[3]/input[@class=&quot;config-editor-textbox&quot;]</value>
      <webElementGuid>c490ab26-117e-4cce-9dd3-9b259da14e53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>95fdd251-0bde-467f-9201-67f1c665ae71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='vif-edit-table']/tr[3]/input</value>
      <webElementGuid>91c5e300-7580-492b-a07e-d089fe2513e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/input</value>
      <webElementGuid>be5e038a-2646-447c-aaa0-99e8ae1b1675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name']</value>
      <webElementGuid>fe3d87f7-0d1a-48df-9403-534e408ad184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
