<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_USB Power Delivery Compliance Test Spe_db7699</name>
   <tag></tag>
   <elementGuidId>be0b5f56-e1f8-4eb5-bf59-d63836f2112e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[3]/div/div/div[2]/div/ul/li/ul/li/ul/li/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.PDMER_PHY_TEST_ALL_UUT.rc-tree-treenode-switcher-open > span.rc-tree-checkbox</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@title=&quot;PDMER_PHY_TEST_ALL_UUT&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@title=&quot;PDMER_PHY_TEST_ALL_UUT&quot;]</value>
      <webElementGuid>a91f7af4-72b5-4f46-ad72-359c4f7ee2c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[3]/div/div/div[2]/div/ul/li/ul/li/ul/li/span[2]</value>
      <webElementGuid>f1b33e31-6f15-40a7-8ced-b96aa6819c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li/span[2]</value>
      <webElementGuid>50a655a2-0674-4db3-b13d-c3cfc137ab6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
