<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Options</name>
   <tag></tag>
   <elementGuidId>545c6297-f6ab-42ef-97bb-d575084e7ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-toggle-group']/label[6]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.leftbarButtonGroup.btn.active.btn-primary > div.custom-setIcon > span.leftnavbar-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a780ec1-e69e-4099-b0c5-6ae4840efc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftnavbar-title</value>
      <webElementGuid>9d8b28d4-56cd-4684-a37d-07e6d13f82de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Options</value>
      <webElementGuid>fd25a829-2f63-400c-b60c-cf55f0715fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-toggle-group&quot;)/label[@class=&quot;leftbarButtonGroup btn active btn-primary&quot;]/div[@class=&quot;custom-setIcon&quot;]/span[@class=&quot;leftnavbar-title&quot;]</value>
      <webElementGuid>88771e3b-07a5-4017-9209-ec4ca9ab6fa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-toggle-group']/label[6]/div/span</value>
      <webElementGuid>ea4a0552-2c79-4eae-ac66-28f1ae6b9d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/following::span[1]</value>
      <webElementGuid>000a8b59-41de-4fb7-ad2c-30ff7664ce2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results'])[1]/following::span[2]</value>
      <webElementGuid>b70ded90-6cd0-4292-b58b-af31250b64cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::span[1]</value>
      <webElementGuid>1bff6839-7c1c-4c13-a017-02b6d8d25c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethernet Connection Settings'])[1]/preceding::span[2]</value>
      <webElementGuid>cb5cc7f6-fa86-44f7-b7b5-9a49d8f9fca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Options']/parent::*</value>
      <webElementGuid>c8d6554e-bec3-4ee2-be0b-31f7d95319cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[6]/div/span</value>
      <webElementGuid>ce4ed2d7-d150-4788-a988-93d60dbd85dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Options' or . = 'Options')]</value>
      <webElementGuid>30ba897b-e49c-42d8-9fd4-00c696a38ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
