<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enable_Debug_Mode_Helpicon</name>
   <tag></tag>
   <elementGuidId>bd1b2c7e-1f0f-4c7a-96d3-f3615cd5488d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[@alt='info-irdrop'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[@alt='info-irdrop'])[8]</value>
   </webElementProperties>
</WebElementEntity>
