<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rerun_Selected_Tests_Checkbox</name>
   <tag></tag>
   <elementGuidId>68f8febc-13fc-4cfc-92c5-92d7a6d29d29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@id='tcRunSelectedTestsCheckBox'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@id='tcRunSelectedTestsCheckBox'])[1]</value>
   </webElementProperties>
</WebElementEntity>
