<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rerun_Selected_Textbox</name>
   <tag></tag>
   <elementGuidId>3a2e3958-ea2c-4bca-8966-9d41b32355b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@id='tcRunSelectedTestInputField'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@id='tcRunSelectedTestInputField'])[1]</value>
   </webElementProperties>
</WebElementEntity>
