<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_Timer_Helpicon</name>
   <tag></tag>
   <elementGuidId>3ef5c32d-a435-44e2-8ef0-3b1d02c640f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[@alt='info-irdrop'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[@alt='info-irdrop'])[7]</value>
   </webElementProperties>
</WebElementEntity>
