<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7th_voltage</name>
   <tag></tag>
   <elementGuidId>1f0ae153-fbc9-4a3f-8fae-8d5ad2698a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class=&quot;config-editor-textbox&quot;])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;config-editor-textbox&quot;])[14]</value>
      <webElementGuid>5c82b945-8f50-4ed0-979d-54f83391c196</webElementGuid>
   </webElementProperties>
</WebElementEntity>
