<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Noise_Type_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>5ac3139b-7ee0-4e8d-88c4-d2cdb5cd1dbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcPdMergedNoiseTypeComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcPdMergedNoiseTypeComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
