<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Connector_Type_dropdown_List</name>
   <tag></tag>
   <elementGuidId>e1b3bb36-7e16-4008-90ff-5a5dae14e044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby=&quot;tcQc3ConnectorTypeComboBox&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby=&quot;tcQc3ConnectorTypeComboBox&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
