<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Connector_Type_Cable_dropdown_List</name>
   <tag></tag>
   <elementGuidId>41768c6e-989c-4349-a90e-e46c2cbefd94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby=&quot;tcQc3ConnectorTypeCableComboBox&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby=&quot;tcQc3ConnectorTypeCableComboBox&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
