<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ports_dropdown_List</name>
   <tag></tag>
   <elementGuidId>3054cd4b-4ace-4d60-b12e-86d07e5ae722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby=&quot;tcQc3PortsComboBox&quot;]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby=&quot;tcQc3PortsComboBox&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
