<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QC_2.0_3.0_Dut_Type_dropdwon_list</name>
   <tag></tag>
   <elementGuidId>7b88e2fb-1201-4d70-b43b-e0dbbd1a7f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby=&quot;tcQc3Qc2.0/3.0DutTypeComboBox&quot;]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby=&quot;tcQc3Qc2.0/3.0DutTypeComboBox&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
