<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QC_Dut_Type_dropdown_List</name>
   <tag></tag>
   <elementGuidId>61bbed8d-8462-4952-bcfb-14113233a69e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby=&quot;tcQc3QcDutTypeComboBox&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby=&quot;tcQc3QcDutTypeComboBox&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
