<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Passed_icon_background_clr</name>
   <tag></tag>
   <elementGuidId>6fa505cc-d1e7-4d1a-b8ee-cf8eb8d4ef50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='tcFilterSelectionPassBtn']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='tcFilterSelectionPassBtn']</value>
   </webElementProperties>
</WebElementEntity>
