<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_warnings_icon_background_clr</name>
   <tag></tag>
   <elementGuidId>6486b948-4fc0-4fec-87d2-802ba56b14d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='tcFilterSelectionWarningBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='tcFilterSelectionWarningBtn']</value>
   </webElementProperties>
</WebElementEntity>
