<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_fail_icon_background_clr</name>
   <tag></tag>
   <elementGuidId>6a7fe8b0-5ab8-4850-b4c4-4ac356db0684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='tcFilterSelectionFailBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='tcFilterSelectionFailBtn']</value>
   </webElementProperties>
</WebElementEntity>
