<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product Capability</name>
   <tag></tag>
   <elementGuidId>710e8d5e-9ea0-41f9-9de7-e8ad8b5e6cb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-toggle-group']/label[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>debd3fe3-72c4-4d5d-80d0-b729e70f4b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-setIcon</value>
      <webElementGuid>2e0fcaaf-44db-4e86-99f9-069c6750cd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Capability</value>
      <webElementGuid>759ee763-796a-43e0-b425-be7ad05eaea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-toggle-group&quot;)/label[@class=&quot;leftbarButtonGroup leftNavItems btn btn-primary&quot;]/div[@class=&quot;custom-setIcon&quot;]</value>
      <webElementGuid>ac2469c0-f03e-42b4-813c-9f0b7c6ff9af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-toggle-group']/label[2]/div</value>
      <webElementGuid>b421cd79-e6ff-4c34-a0dd-9670372a6367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connection Setup'])[1]/following::div[1]</value>
      <webElementGuid>1c2a5242-b6a4-4487-80c7-2d62b39564cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set App Mode :'])[1]/following::div[13]</value>
      <webElementGuid>1c59b0c2-c8a0-480e-b591-b31fa0be522a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Config'])[1]/preceding::div[1]</value>
      <webElementGuid>f4efdaf1-2185-4c8a-b5f5-43cf09c76322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div</value>
      <webElementGuid>93cc8d8e-b5db-4670-b00a-bd10306e8d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Product Capability' or . = 'Product Capability')]</value>
      <webElementGuid>71201018-be16-420c-a474-508d6a292250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
