<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Noise_Type_Dropdown_List</name>
   <tag></tag>
   <elementGuidId>c8dacad3-11d3-47e7-acae-fd5d4d1ee3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcPd2CommunicationNoiseTypeComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcPd2CommunicationNoiseTypeComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
