<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Vconn_Type_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>7494f857-94e1-4fd8-8f51-21ed00d7cbf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcPd2CommunicationVconnVlotageComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcPd2CommunicationVconnVlotageComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
