<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_C2_Update_Firmware_dialogue</name>
   <tag></tag>
   <elementGuidId>2a22ec27-202e-4120-a85e-f45a029fc149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@class='popup-heder-font-align']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[@class='popup-heder-font-align']</value>
   </webElementProperties>
</WebElementEntity>
