<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cable_Type</name>
   <tag></tag>
   <elementGuidId>02b3f262-40f1-4b70-a08a-5cfd68551714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/button[@id='pcPort1CableSelectionComboBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/button[@id='pcPort1CableSelectionComboBox']</value>
   </webElementProperties>
</WebElementEntity>
