<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DP_Device_Type_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>47da60f5-79c5-4a66-bcad-b6d5567679e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcDisplayPortDPDeviceTypeComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcDisplayPortDPDeviceTypeComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
