<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DP_Sink_Type_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>46f0bf2c-31d3-4a34-9935-51fd95ade279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcDisplayPortDPSinkTypeComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcDisplayPortDPSinkTypeComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
