<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DP_Device_Capability_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>fd80a013-f206-4481-a518-2eaab8ed2614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcDisplayPortDPDeviceCapabilityComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcDisplayPortDPDeviceCapabilityComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
