<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enable_Port3_Toggle</name>
   <tag></tag>
   <elementGuidId>fba9c21e-85c3-461c-9ca9-3da7721e064b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div[@id=&quot;opFivePortTestingTab3EnablePortToggleSwitch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div[@id=&quot;opFivePortTestingTab3EnablePortToggleSwitch&quot;]</value>
   </webElementProperties>
</WebElementEntity>
