<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enable_Port5_Toggle</name>
   <tag></tag>
   <elementGuidId>7f2fc451-ae2b-43d5-9c09-f744bf44e734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div[@id=&quot;opFivePortTestingTab5EnablePortToggleSwitch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div[@id=&quot;opFivePortTestingTab5EnablePortToggleSwitch&quot;]</value>
   </webElementProperties>
</WebElementEntity>
