<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Live_status</name>
   <tag></tag>
   <elementGuidId>c1963c0a-faeb-4bad-9a7b-b8b0b6cebb86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@class=&quot;plot-toolbar-live-updates-btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@class=&quot;plot-toolbar-live-updates-btn&quot;]</value>
      <webElementGuid>56e41b73-044c-412e-9bb9-4410fff62946</webElementGuid>
   </webElementProperties>
</WebElementEntity>
