<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Device_Type_dropdown</name>
   <tag></tag>
   <elementGuidId>d39af3e5-0656-4227-9ded-44dd680a0603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;tcDisplayPortDPDeviceTypeComboBox&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tcTBTNumberOfPortsComboBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tcTBTDeviceTypeComboBox'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;tcDisplayPortDPDeviceTypeComboBox&quot;]</value>
      <webElementGuid>7031b67a-562e-4078-b264-31774531a5a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>67f7636a-0f76-4f36-921f-187b3a0bc6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[3]/div/div[2]/div/div/div/div/div[7]/div/table/tbody/tr/td[2]/div/button</value>
      <webElementGuid>0ddeb96e-3050-4aef-9c9d-a89ae7995e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number Of Ports'])[1]/following::button[1]</value>
      <webElementGuid>f6f07444-c3c1-4b0c-8600-f5a464c3f61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[1]/following::button[1]</value>
      <webElementGuid>7e4bee0c-97be-4588-a644-2867a71aa683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered Type'])[1]/preceding::button[1]</value>
      <webElementGuid>e3f9e218-b931-48dc-9270-10eb09818918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[3]/preceding::button[1]</value>
      <webElementGuid>7c54c21f-515c-4a37-bf7f-c333595e4521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/table/tbody/tr/td[2]/div/button</value>
      <webElementGuid>fcec841c-31f7-4109-ba1f-3159e289d16a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
