<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Device_Type_Drpdown_List</name>
   <tag></tag>
   <elementGuidId>60679eab-a1b4-41cd-a479-e0e4f2c08ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-labelledby='tcTBTDeviceTypeComboBox']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-labelledby='tcTBTDeviceTypeComboBox']/a</value>
   </webElementProperties>
</WebElementEntity>
