<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Device_URL</name>
   <tag></tag>
   <elementGuidId>5ed458e3-a4e2-4150-8b8e-e24845ffd97e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tcUSB-CFunctionalDeviceURLInputField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tcUSB-CFunctionalDeviceURLInputField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tcUSB-CFunctionalDeviceURLInputField</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>usbPanelcontrol textbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-area&quot;]/div[@class=&quot;app-area-bottom&quot;]/div[@class=&quot;main-area&quot;]/div[@class=&quot;scroll-area&quot;]/div[1]/div[@class=&quot;scroll-content-sticky&quot;]/div[@class=&quot;scroll-panel panel-container mobile-container&quot;]/div[@class=&quot;right-border panel-padding report-generation-container&quot;]/div[@class=&quot;panel-div moi-maincontainer&quot;]/div[1]/div[@class=&quot;panel-setWidth&quot;]/div[@class=&quot;scroll moi-container&quot;]/div[9]/div[1]/table[@class=&quot;table table-striped table-bordered table-hover&quot;]/tbody[1]/tr[3]/td[@class=&quot;usb-td-label&quot;]/input[@id=&quot;tcUSB-CFunctionalDeviceURLInputField&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tcUSB-CFunctionalDeviceURLInputField']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[3]/div/div[2]/div/div/div/div/div[9]/div/table/tbody/tr[3]/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
