<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Disable_Popups</name>
   <tag></tag>
   <elementGuidId>d662cc28-9c76-4dbb-a321-57a046d5a13f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;disablePopups&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;disablePopups&quot;]</value>
      <webElementGuid>46d889bb-90ca-4523-8b74-35374b478a1a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
