<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_StartExecution_Disable</name>
   <tag></tag>
   <elementGuidId>9f4f22bb-a7e2-4ecf-a1f3-78cbe8b9ade1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='tcStartAndStopExecutionBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='tcStartAndStopExecutionBtn']</value>
   </webElementProperties>
</WebElementEntity>
