<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Options_Testsuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>100</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8715b542-d733-4257-9521-98fcbe63d769</testSuiteGuid>
   <testCaseLink>
      <guid>af37c9d9-ffca-490e-ac27-e9fa708fb18b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Options_Page/7.2_Config_Controller/Test_7.2.1_Configure_Panel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5a8d961-43ed-434e-a573-4ea6fa85845e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2601e6b-9f2b-40bf-a91c-05194b190b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08c9ba49-e90f-4fb4-8227-8ac7d6f4d528</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7bc8800-f8f2-43f0-9e63-8ade4d5028e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5086b73-65b4-4375-a232-e4b5fa25247b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69b92784-fa07-4f7f-8467-6043817bba74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db434efa-1cda-40e1-b634-c8cd30869692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aabc0f3-fe8b-4ede-8b78-f18f8be6551c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0fee9c5-81f4-4817-92b4-bfc79ca2e5ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Options_Page/7.2_Config_Controller/Test_7.2.2_Send_Message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3d12ef2c-0bc2-4dc1-90c3-4a43fe365369</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Options_Page/Cable_IR_Drop_Calibration/Test_7.3_Cable_IR_Drop_Calibration</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
