<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Report_Testsuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>100</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b08c9fbd-0d7d-432e-8c16-9a50dd8c30c8</testSuiteGuid>
   <testCaseLink>
      <guid>74bb7e0f-039c-4c09-961c-5586d88f773e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report_Page/Test_6.1_Report_Panel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>561df39d-88b4-41da-a878-3c47a5f15241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bd0a846-7ecc-497c-b6ce-3964ef75b520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eda90c7c-3056-437e-98b5-23aed7656442</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9839ddca-b79f-49c2-b265-8e202afbc428</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb846e86-f66c-432b-ba97-c983073ee8ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c60c25d4-87c6-4faa-8bb1-7bda7d50ae45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report_Page/Test_6.2_Detailed_Report_Structure</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>22fb8753-8b44-4e52-a96a-e26d355dbb8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report_Page/Test_6.3_View_Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77b1a7a4-6f93-484c-a589-8560bc7ae8c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>508a98db-580b-461f-a4e6-54a7854fd6e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report_Page/Test_6.4_Download_Current_HTML_Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7818441-7c64-4bd4-a5aa-64d08c205aeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a95aca6-1bd6-4803-95f9-6d33a8d3a2ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec41144-8018-4ffd-bd10-07ebb2688bc1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b56e39ae-6a6a-4774-8fd5-669cb9cc3be1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report_Page/Test_6.5_Download_Current_DUT_Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fdbbb36-5444-4363-a306-d708abe13db6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1570bb9b-dc16-4e4f-8a4b-079d40d4d50e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Report_Page/Test_6.6_Report_Data_Management</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eb907de-a74d-4a28-a592-d5f89f98b8cb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
