<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cabel_Help_Icon</name>
   <tag></tag>
   <elementGuidId>d06136e4-74fd-482f-abd3-f53482aa4fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='product-caps-cable-selection-info-icon']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='product-caps-cable-selection-info-icon']/img</value>
   </webElementProperties>
</WebElementEntity>
